name: mm
channels:
  - plotly
  - conda-forge
dependencies:
  - python=3.8
  - plotly
  - plotly-orca
  - rpy2
  - pip
  - pip:
    - numpydoc
    - psutil
    - pep517
    - twine
    - black
    - isort
    - tox
    - pytest
    - pytest-cov
    - -e .
